blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path('list_blog/', cache_page(60)(BlogListView.as_view()), name='list_blog'),
    path('view_blog/<int:pk>/', BlogDetailView.as_view(), name='view_blog'),
    path('create_blog/', BlogCreateView.as_view(), name='create_blog'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete_blog/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),]

clients/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from .views import RegisterView, VerifyEmailView, message_view, invalid_token_view, ProfileView
from clients.apps import ClientsConfig

app_name = ClientsConfig.name

urlpatterns = [
    path('login', LoginView.as_view(template_name='clients/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(template_name='clients/register.html'), name='register'),
    path('verify_email/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),
    path('email_check_message/', message_view, name='email_check_message'),
    path('invalid_token/', invalid_token_view, name='invalid_token'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.views import index, MailingCreateView, MessageCreateView, MailingListView, MailingDeleteView, \
    MailingUpdateView, MessageListView, MessageDeleteView, MessageUpdateView, ClientCreateView, ClientListView, \
    ClientDeleteView, ClientUpdateView, start_mailing, stop_mailing

urlpatterns = [
    path('', index, name='index'),
    path('create_mailing/', MailingCreateView.as_view(), name='create_mailing'),
    path('list_mailing/', MailingListView.as_view(), name='list_mailing'),
    path('delete_mailing/<int:pk>/', MailingDeleteView.as_view(), name='delete_mailing'),
    path('edit_mailing/<int:pk>/', MailingUpdateView.as_view(), name='edit_mailing'),
    path('create_message/', MessageCreateView.as_view(), name='create_message'),
    path('list_message/', MessageListView.as_view(), name='list_message'),
    path('delete_message/<int:pk>/', MessageDeleteView.as_view(), name='delete_message'),
    path('edit_message/<int:pk>/', MessageUpdateView.as_view(), name='edit_message'),
    path('create_client/', ClientCreateView.as_view(), name='create_client'),
    path('list_client/', ClientListView.as_view(), name='list_client'),
    path('delete_client/<int:pk>/', ClientDeleteView.as_view(), name='delete_client'),
    path('edit_client/<int:pk>/', ClientUpdateView.as_view(), name='edit_client'),
    path('start_mailing/<int:pk>/', start_mailing, name='start_mailing'),
    path('stop_mailing/<int:pk>/', stop_mailing, name='stop_mailing'),
]

clients/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class Author(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="email")
    full_name = models.CharField(max_length=100, verbose_name='full name')
    organization = models.CharField(max_length=100, null=True, blank=True)
    avatar = models.ImageField(null=True, blank=True)
    is_active = models.BooleanField(default=False)
    is_baned = models.BooleanField(default=False)
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []


class VerificationToken(models.Model):
    user = models.ForeignKey(Author, on_delete=models.CASCADE)
    token = models.TextField(max_length=255)
    is_active = models.BooleanField(default=True)

mailing/models.py
from django.db import models

from clients.models import Author

class Message(models.Model):
    subject = models.CharField(max_length=200)
    body = models.TextField()
    def __str__(self):
        return f"Тема:{self.subject}\nПисьмо:{self.body}"

class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name="email")
    full_name = models.CharField(max_length=100)
    comment = models.TextField()

class Mailing(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True, verbose_name='name')
    send_time = models.DateTimeField()

    frequency = models.CharField(max_length=2, choices=[
        ('1', 'Раз в день'),
        ('7', 'Раз в неделю'),
        ('30', 'Раз в месяц'),
    ])

    status = models.CharField(choices=[

        ('created', 'Создана'),
        ('started', 'Запущена'),
        ('completed', 'Завершена'),
        ],
        max_length=50)
    clients = models.ManyToManyField(Client)
    messages = models.ManyToManyField(Message)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.status}, {self.send_time}'
    class Meta:
        verbose_name_plural = 'Mailings'

class MailingLog(models.Model):
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=200)
    server_response = models.TextField(null=True, blank=True)

clients/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from clients.models import Author


class AuthorRegisterForm(UserCreationForm):
    class Meta:
        model = Author
        fields = ('email', 'password1', 'password2')


class AuthorProfileForm(UserChangeForm):
    class Meta:
        model = Author
        fields = ('email', 'full_name', 'organization', 'avatar',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

mailing/forms.py
from django import forms
from tempus_dominus.widgets import DateTimePicker
from mailing.models import Mailing, Message, Client


class MailingForm(forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('name', 'send_time', 'frequency', 'messages', 'clients', )
        widgets = {
            'send_time': DateTimePicker(
                options={
                    'format': 'YYYY-MM-DD HH:mm',
                    'sideBySide': True,
                },
                attrs={
                    'placeholder': 'Введите формат даты и времени: ГГГГ-ММ-ДД ЧЧ:мм',
                }
            )
        }


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('subject', 'body', )


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('email', 'full_name', 'comment', )

clients/views.py
import string
import random

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from clients.forms import AuthorRegisterForm, AuthorProfileForm
from clients.models import Author, VerificationToken
from config import settings


class RegisterView(CreateView):
    model = Author
    form_class = AuthorRegisterForm
    template_name = 'clients/register.html'
    success_url = reverse_lazy('clients:email_check_message')

    def generate_random_password(self):
        length = 12
        characters = string.ascii_letters + string.digits + string.punctuation
        password = ''.join(random.choice(characters) for _ in range(length))
        return password

    def form_valid(self, form):

        author = form.save()

        token = default_token_generator.make_token(author)
        token_object = VerificationToken(user=author, token=token)
        token_object.save()
        verify_url = self.request.build_absolute_uri(reverse_lazy('clients:verify_email', kwargs={'token': token}))

        send_mail(
            subject='Подтвердите ваш адрес электронной почты',
            message=f'Привет! Пожалуйста, подтвердите свою электронную почту, перейдя по ссылке: {verify_url}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[author.email],
        )
        return super().form_valid(form)



class VerifyEmailView(TemplateView):
    def get(self, request, *args, **kwargs):
        token = self.kwargs['token']
        verified_token = get_object_or_404(VerificationToken, token=token)

        if verified_token.is_active:
            author = verified_token.user
            author.is_active = True
            author.save()

            verified_token.is_active = False
            verified_token.save()

            return redirect('clients:login')
        return redirect('clients:invalid_token')


class ProfileView(LoginRequiredMixin, UpdateView):
    model = Author
    form_class = AuthorProfileForm
    success_url = reverse_lazy('index')

    def get_object(self, queryset=None):
        return self.request.user


def message_view(request):
    return render(request, 'clients/email_check_message.html')

def invalid_token_view(request):
    return render(request, 'clients/invalid_token.html')

mailing/views.py
from random import sample
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page, never_cache
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView
from blog.models import Blog
from clients.models import Author
from config import settings
from mailing.forms import MailingForm, MessageForm, ClientForm
from mailing.models import Mailing, Message, Client, MailingLog
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, reverse
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.conf import settings
import time

from mailing.services import logging_func


def is_not_manager(user):
    return not user.groups.filter(name='manager').exists()


@cache_page(60)
def index(request):
    author = Author.objects.first()
    blogs = Blog.objects.all()

    if blogs.count() >= 3:
        random_blogs = sample(list(blogs), 3)
    else:
        random_blogs = list(blogs)

    total_mailings = Mailing.objects.count()
    active_mailings = 0
    unique_clients = 0

    if request.user.is_authenticated:
        active_mailings = Mailing.objects.filter(status='started', author=request.user).count()
        unique_clients = Client.objects.values('email').distinct().count()

    return render(request, 'mailing/index.html', {
        'author': author,
        'random_blogs': random_blogs,
        'total_mailings': total_mailings,
        'active_mailings': active_mailings,
        'unique_clients': unique_clients,
    })

@method_decorator(user_passes_test(is_not_manager), name='dispatch')
class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('list_mailing')

    def test_func(self):
        return self.request.author.is_authenticated

    def form_valid(self, form):
        form.instance.status = 'created'
        form.instance.author = self.request.user
        return super().form_valid(form)

@method_decorator(user_passes_test(is_not_manager), name='dispatch')
class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('list_mailing')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['formset'] = MailingForm
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']()
        formset.data = self.request.POST
        formset.is_bound = True

        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            raise self.form_invalid(form)

@method_decorator(login_required, name='dispatch')
class MailingListView(ListView):
    model = Mailing

    def get_template_names(self):
        if self.request.user.groups.filter(name='manager').exists():
            template_name = 'for_manager/manager_mailing_list.html'
        else:
            template_name = 'mailing/mailing_list.html'
        return [template_name]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

@method_decorator(user_passes_test(is_not_manager), name='dispatch')
class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('list_mailing')



def start_mailing(request, pk):
    mailing = get_object_or_404(Mailing, pk=pk)
    if mailing.send_time >= timezone.now() and mailing.status != 'started':

        mailing.status = 'started'
        mailing.save()

    return HttpResponseRedirect(reverse('list_mailing'))


def stop_mailing(request, pk):
    mailing = get_object_or_404(Mailing, pk=pk)
    if mailing.status == 'started':
        mailing.status = 'completed'
        mailing.save()
        logging_func(mailing=mailing, status='mailing is finished', response=HttpResponse())

    return redirect("list_mailing")

@method_decorator(user_passes_test(is_not_manager), name='dispatch')
class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('list_message')

@method_decorator(user_passes_test(is_not_manager), name='dispatch')
class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('list_message')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['formset'] = MessageForm
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']()
        formset.data = self.request.POST
        formset.is_bound = True

        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            raise self.form_invalid(form)


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_template_names(self):
        if self.request.user.groups.filter(name='manager').exists():
            template_name = 'for_manager/manager_message_list.html'
        else:
            template_name = 'mailing/message_list.html'
        return [template_name]
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

@method_decorator(user_passes_test(is_not_manager), name='dispatch')
class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('list_message')

@method_decorator(user_passes_test(is_not_manager), name='dispatch')
class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('list_client')


@method_decorator(user_passes_test(is_not_manager), name='dispatch')
class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/client_form.html'
    success_url = reverse_lazy('list_client')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.request.POST:
            context_data['formset'] = ClientForm(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = ClientForm(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name = 'mailing/list_client.html'
    def get_template_names(self):
        if self.request.user.groups.filter(name='manager').exists():
            template_name = 'for_manager/manager_client_list.html'
        else:
            template_name = 'mailing/client_list.html'
        return [template_name]

@method_decorator(user_passes_test(is_not_manager), name='dispatch')
class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('list_client')

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-12">
  <div class="row mb-12">
    <div class="col-6">
      <div class="row g-0">
        <div class="card">
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
                <p>Вы уверены, что хотите удалить?</p>
                <p>{{ object.full_name }}</p>
              <button type="submit" class="btn btn-success">Да</button>
              <a href="{%url 'list_client' %}" class="btn btn-danger">Нет</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}
{% load static %}

{% block content %}

<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {% if object %}
    <button type="submit" class="btn btn-success">Update</button>
    {% else %}
    <button type="submit" class="btn btn-success">Create</button>
    {% endif %}
</form>
</body>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
<div><p class="lead">
    <a href="{% url 'create_client' %}" class="btn btn-lg btn-light fw-bold border-white bg-white">Создать нового клиента</a>
</p>
</div>
{% for object in object_list %}

<div class="container px-4 py-5" id="hanging-icons">
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="col d-flex align-items-start">
                <svg class="bi" width="1em" height="1em">
                    <use xlink:href="#toggles2"/>
                </svg>
            </div>
            <div>
                <h3 class="fs-2 text-body-emphasis">{{ object.full_name }}</h3>
                <p>Email: - {{ object.email }}</p>
                <p>Comment: - {{ object.comment }}</p>

                <a href="{% url 'edit_client' object.pk %}" class="btn btn-warning">
                    Редактровать
                </a>
                <a href="{% url 'delete_client' object.pk %}" class="btn btn-danger">
                    Удалить
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endblock %}

mailing/templates/mailing/index.html
{% extends 'mailing/base.html' %}
{% load static %}

{% block content %}
<div class="main">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>Сервис для рассылок E-mail</h1>
                {% if user.is_authenticated %}
                <p class="lead">
                    <a href="{% url 'list_mailing' %}" class="btn btn-lg btn-light fw-bold border-white bg-white">К
                        рассылкам</a>
                <p class="text-white">Количество рассылок: {{ total_mailings }}</p>
                </p>
                <p class="text-white">Количество активных рассылок: {{ active_mailings }}</p>
                </p>
                <p class="lead">
                    <a href="{% url 'list_message' %}" class="btn btn-lg btn-light fw-bold border-white bg-white">К
                        письмам</a>
                </p>
                <p class="lead">
                    <a href="{% url 'list_client' %}" class="btn btn-lg btn-light fw-bold border-white bg-white">К
                        клиентам</a>
                <p class="text-white">Количество клиентов: {{ unique_clients }}</p>
                </p>
                <p class="lead">
                    <a href="{% url 'clients:profile' %}"
                       class="btn btn-lg btn-light fw-bold border-white bg-white">Профиль</a>
                </p>

            </div>
            <div class="col-md-6">
                {% for blog in blogs %}
                <div class="text-center mt-4">
                    <h3 class="fs-2 text-body-emphasis">{{ blog.title }}</h3>
                    <p>{{ blog.content | truncatechars:50 }}</p>
                    <a href="#" class="icon-link">
                        Перейти к блогу
                        <svg class="bi">
                            <use xlink:href="#chevron-right"/>
                        </svg>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="row mt-4">
    <div class="col-md-12">
        <p class="lead">Войдите в аккаунт или зарегистрируйтесь</p>
        <p class="lead">
            <a href="{% url 'clients:login' %}" class="btn btn-lg btn-light fw-bold border-white bg-white">Войти</a>
        </p>
        <a href="{% url 'clients:register' %}" class="btn btn-lg btn-light fw-bold border-white bg-white">Зарегистрироваться</a>
    </div>
</div>
{% endif %}
</div>
{% if user.is_authenticated %}
<footer class="mt-auto text-white-50">
    <p><a href="{% url 'clients:logout' %}" class="text-white">Выйти</a>.</p>
</footer>
</div>
{% endif %}
</div>
</div>
{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-12">
  <div class="row mb-12">
    <div class="col-6">
      <div class="row g-0">
        <div class="card">
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
                <p>Вы уверены, что хотите удалить?</p>
                <p>{{ object.name }}</p>
              <button type="submit" class="btn btn-success">Да</button>
              <a href="{%url 'list_mailing' %}" class="btn btn-danger">Нет</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}
{% load static %}

{% block content %}

<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {% if object %}
    <button type="submit" class="btn btn-success">Update</button>
    {% else %}
    <button type="submit" class="btn btn-success">Create</button>
    {% endif %}
</form>
</body>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}
<div>
    <p class="lead">
        <a href="{% url 'create_mailing' %}" class="btn btn-lg btn-light fw-bold border-white bg-white">Создать новую
            настройку рассылки</a>
    </p>
</div>
{% for object in object_list %}
<div class="container px-4 py-5" id="hanging-icons">
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
        <div class="col d-flex align-items-start">
            <svg class="bi" width="1em" height="1em">
                <use xlink:href="#toggles2"/>
            </svg>
        </div>

        <div>
            <h3 class="fs-2 text-body-emphasis">{{ object.name }}</h3>
            <p>Send time - {{ object.send_time }}</p>
            <p>Frequency - {{ object.frequency }}</p>
            <p>Status - {{ object.status }}</p>
                {% if object.status == 'created' %}
                <a href="{% url 'start_mailing' object.pk %}" class="btn btn-info">
                    Запустить
                </a>
                {% elif object.status == 'started' %}
                <p>Рассылка выполняется...</p>
                <a href="{% url 'stop_mailing' object.pk %}" class="btn btn-info">
                    Завершить
                </a>
                {% elif object.status == 'completed' %}
                <p>Рассылка завершена.</p>
                <a href="{% url 'start_mailing' object.pk %}" class="btn btn-info">
                    Запустить снова
                </a>
                {% endif %}
                <a href="{% url 'edit_mailing' object.pk %}" class="btn btn-warning">
                    Редактировать
                </a>
                <a href="{% url 'delete_mailing' object.pk %}" class="btn btn-danger">
                    Удалить
                </a>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

mailing/templates/mailing/message_confirm_delete.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-12">
  <div class="row mb-12">
    <div class="col-6">
      <div class="row g-0">
        <div class="card">
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
                <p>Вы уверены, что хотите удалить?</p>
                <p>Письмо "{{ object.subject }}"</p>
              <button type="submit" class="btn btn-success">Да</button>
              <a href="{%url 'list_message' %}" class="btn btn-danger">Нет</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

mailing/templates/mailing/message_form.html
{% extends 'mailing/base.html' %}
{% load static %}

{% block content %}

<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {% if object %}
    <button type="submit" class="btn btn-success">Update</button>
    {% else %}
    <button type="submit" class="btn btn-success">Create</button>
    {% endif %}
</form>
</body>
{% endblock %}