blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path('list_blog/', cache_page(60)(BlogListView.as_view()), name='list_blog'),
    path('view_blog/<int:pk>/', BlogDetailView.as_view(), name='view_blog'),
    path('create_blog/', BlogCreateView.as_view(), name='create_blog'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit_blog'),
    path('delete_blog/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name='title')
    content = models.TextField(verbose_name='content')
    image = models.ImageField(verbose_name='image', null=True, blank=True)
    view_count = models.IntegerField(null=True, blank=True, verbose_name='view_count')
    date_published = models.DateTimeField(auto_now_add=True, verbose_name='date')

blog/forms.py
from django import forms

from blog.models import Blog


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', 'image',)

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy, reverse
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from blog.forms import BlogForm
from blog.models import Blog


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:list_blog')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return context_data

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save(commit=False)
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()
            return super().form_valid(form)
        else:
            return self.form_valid(form)

class BlogListView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'
    context_object_name = 'blogs'

class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:list_blog')


class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog


    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.view_count is None:
            self.object.view_count = 0
        self.object.view_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list_blog')

blog/templates/blog/blog_confirm_delete.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-12">
  <div class="row mb-12">
    <div class="col-6">
      <div class="row g-0">
        <div class="card">
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
                <p>Хотите удалить этот блог?</p>
                {{ object.title }}
              <button type="submit" class="btn btn-warning">Да</button>
              <a href="{%url 'blog:list_blog' %}" class="btn btn-success">Нет</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

 <div class="row mb-2">
    <div class="col-md-12">
      <div class="row g-0">
        <div class="col p-4">
          <strong class="d-inline-block mb-2 text-primary-emphasis">{{ object.title }}</strong>
          <h3 class="mb-0"> Views: {{ object.view_count }}</h3>
          <div class="mb-1 text-body-secondary">{{ object.created_date }}</div>
        </div>
        <div class="col-auto d-none d-lg-block">
          <img src="{{ object.preview|mediapath }}" />
        </div>
          <div>
              <p class="card-text">{{ object.content }}</p>
          <div class="dtn-group">
            <a href="{%url 'blog:edit_blog' object.pk %}" type="button"
            class="btn btn-sm btn-outline-secondary">Edit</a>
              <a href="{%url 'blog:delete_blog' object.pk %}" type="button"
            class="btn btn-sm btn-outline-secondary">Delete</a>
          </div>
    </div>
      </div>
    </div>
 </div>


{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

<div class="col-12">
  <div class="row mb-12">
    <div class="col-8">
      <div class="row g-0">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">
              Создать блог
            </h4>
          </div>
          <div class="card-body">
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <button type="submit" class="btn btn-success">Create</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'mailing/base.html' %}
{% load my_tags %}
{% block content %}

<div class="row">
  <div class="col-6">
    <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="create_blog/">Создать блок</a></li>
        </ul>
  </div>
</div>
{% for object in object_list %}
 <div class="row-12">
  <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
    <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
      <div class="my-3 p-3">
        <h2 class="display-5">{{ object.title }}</h2>
          <div class="col-auto d-none d-lg-block">
          <img src="{{ object.preview|mediapath }}" />
          </div>
        <p class="text">{{ object.content|slice:":100" }}</p>
          <p class="lead">
              <a href="{% url 'blog:view_blog' pk=object.pk %}" class="btn btn-lg btn-light fw-bold border-white bg-white">К
                  блогу</a>
          </p>
      </div>
      <div class="bg-white box-shadow mx-auto" style="width: 80%; height: 300px; border-radius: 21px 21px 0 0;"></div>
    </div>
  </div>
</div>
{% endfor %}

{% endblock %}